In [37]:
import pandas as pd
from pathlib import Path
import matplotlib.pyplot as plt

# Closure Feed Analysis

In [17]:
alerts_path = Path.cwd() / 'Road_Closure_Feeds'

closures_df = pd.concat(
    [pd.read_csv(f) for f in alerts_path.iterdir() if f.suffix.lower() == ".csv"],
    ignore_index=True
)

In [35]:
closures_df.head()

,extraction_date,name,data_source_id,event_type,road_names,direction,description,organization_name,update_date,contact_name,contact_email
0,2026-03-13,North Entrance Road and Rim Drive are CLOSED f...,02e0312b-cbd4-40bb-2c4e-08d4c7ad36e2,incident,"['North Entrance Road', 'West Rim Drive', 'Eas...",eastbound,Seasonal closure of North Entrance Road and Ri...,Crater Lake National Park,2024-02-01T01:07:37.430224Z,Crater Lake National Park,CRLA_Superintendent@nps.gov
1,2026-03-13,North Entrance Road and Rim Drive are CLOSED f...,02e0312b-cbd4-40bb-2c4e-08d4c7ad36e2,incident,"['North Entrance Road', 'West Rim Drive', 'Eas...",northbound,Seasonal closure of North Entrance Road and Ri...,Crater Lake National Park,2024-02-01T01:07:37.430224Z,Crater Lake National Park,CRLA_Superintendent@nps.gov
2,2026-03-13,North Entrance Road and Rim Drive are CLOSED f...,02e0312b-cbd4-40bb-2c4e-08d4c7ad36e2,incident,"['North Entrance Road', 'West Rim Drive', 'Eas...",northbound,Seasonal closure of North Entrance Road and Ri...,Crater Lake National Park,2024-02-01T01:07:37.430224Z,Crater Lake National Park,CRLA_Superintendent@nps.gov
3,2026-03-13,North Entrance Road and Rim Drive are CLOSED f...,02e0312b-cbd4-40bb-2c4e-08d4c7ad36e2,incident,"['North Entrance Road', 'West Rim Drive', 'Eas...",southbound,Seasonal closure of North Entrance Road and Ri...,Crater Lake National Park,2024-02-01T01:07:37.430224Z,Crater Lake National Park,CRLA_Superintendent@nps.gov
4,2026-03-13,North Entrance Road and Rim Drive are CLOSED f...,02e0312b-cbd4-40bb-2c4e-08d4c7ad36e2,incident,"['North Entrance Road', 'West Rim Drive', 'Eas...",northbound,Seasonal closure of North Entrance Road and Ri...,Crater Lake National Park,2024-02-01T01:07:37.430224Z,Crater Lake National Park,CRLA_Superintendent@nps.gov

## Number of Closures Over Time

In [41]:
closure_count_by_park = pd.pivot_table(
    closures_df,
    values='event_type',
    index = 'organization_name',
    columns='extraction_date',
    aggfunc='count'
)
closure_count_by_park = closure_count_by_park.fillna(0).astype(int)
closure_count_by_park

extraction_date,2026-03-13,2026-03-14,2026-03-15,2026-03-16
organization_name,,,,
Black Canyon of the Gunnison National Park,8,8,8,8
Blue Ridge Parkway,20,20,20,20
Buffalo National River,2,2,2,2
Crater Lake National Park,10,10,10,10
Curecanti National Recreation Area,2,2,2,2
Delaware Water Gap,18,18,18,18
Golden Gate National Recreation Area,2,2,2,2
Grand Canyon National Park,6,6,6,6
Great Basin National Park,8,8,8,8
Great Smoky Mountains National Park,23,23,23,31
Guadalupe Mountains National Park,2,2,2,2
Katahdin Woods and Waters National Monument,4,4,4,4
Lassen Volcanic,22,22,22,22
Mount Rainier,2,2,2,2
Natchez Trace Parkway,2,2,2,2
Ozark National Scenic Riverways,2,2,2,2
Padre Island National Seashore,2,2,2,2
Petersburg,16,16,16,16
Sequoia & Kings Canyon National Parks,42,42,42,42
Yosemite National Park,6,6,6,6

# Alerts Feed Analysis

In [20]:
alerts_path = Path.cwd() / 'Alerts_Feeds'

alerts_df = pd.concat(
    [pd.read_csv(f) for f in alerts_path.iterdir() if f.suffix.lower() == ".csv"],
    ignore_index=True
)

## Number of Alerts Over Time

In [42]:
alerts_count_by_park = pd.pivot_table(
    alerts_df,
    values='id',
    index = 'parkCode',
    columns='extraction_date',
    aggfunc='count'
)
alerts_count_by_park = alerts_count_by_park.fillna(0).astype(int)
alerts_count_by_park

extraction_date  2026-03-13  2026-03-14  2026-03-15  2026-03-16
parkCode
abli                      0           0           0           1
acad                      1           1           1           1
adam                      3           3           3           3
afbg                      1           1           1           1
agfo                      2           2           2           2
...                     ...         ...         ...         ...
yell                      4           4           4           3
york                      1           1           1           1
yose                      1           1           1           1
yuch                      1           1           1           1
zion                      5           5           5           5

[305 rows x 4 columns]